/*
 * Strava API v3
 *
 * The [Swagger Playground](https://developers.strava.com/playground) is the easiest way to familiarize yourself with the Strava API by submitting HTTP requests and observing the responses before you write any client code. It will show what a response will look like with different endpoints depending on the authorization scope you receive from your athletes. To use the Playground, go to https://www.strava.com/settings/api and change your “Authorization Callback Domain” to developers.strava.com. Please note, we only support Swagger 2.0. There is a known issue where you can only select one scope at a time. For more information, please check the section “client code” at https://developers.strava.com/docs.
 *
 * The version of the OpenAPI document: 3.0.0
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SportType : An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)
/// An enumeration of the sport types an activity may have. Distinct from ActivityType in that it has new types (e.g. MountainBikeRide)
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum SportType {
    #[serde(rename = "AlpineSki")]
    AlpineSki,
    #[serde(rename = "BackcountrySki")]
    BackcountrySki,
    #[serde(rename = "Badminton")]
    Badminton,
    #[serde(rename = "Canoeing")]
    Canoeing,
    #[serde(rename = "Crossfit")]
    Crossfit,
    #[serde(rename = "EBikeRide")]
    EBikeRide,
    #[serde(rename = "Elliptical")]
    Elliptical,
    #[serde(rename = "EMountainBikeRide")]
    EMountainBikeRide,
    #[serde(rename = "Golf")]
    Golf,
    #[serde(rename = "GravelRide")]
    GravelRide,
    #[serde(rename = "Handcycle")]
    Handcycle,
    #[serde(rename = "HighIntensityIntervalTraining")]
    HighIntensityIntervalTraining,
    #[serde(rename = "Hike")]
    Hike,
    #[serde(rename = "IceSkate")]
    IceSkate,
    #[serde(rename = "InlineSkate")]
    InlineSkate,
    #[serde(rename = "Kayaking")]
    Kayaking,
    #[serde(rename = "Kitesurf")]
    Kitesurf,
    #[serde(rename = "MountainBikeRide")]
    MountainBikeRide,
    #[serde(rename = "NordicSki")]
    NordicSki,
    #[serde(rename = "Pickleball")]
    Pickleball,
    #[serde(rename = "Pilates")]
    Pilates,
    #[serde(rename = "Racquetball")]
    Racquetball,
    #[serde(rename = "Ride")]
    Ride,
    #[serde(rename = "RockClimbing")]
    RockClimbing,
    #[serde(rename = "RollerSki")]
    RollerSki,
    #[serde(rename = "Rowing")]
    Rowing,
    #[serde(rename = "Run")]
    Run,
    #[serde(rename = "Sail")]
    Sail,
    #[serde(rename = "Skateboard")]
    Skateboard,
    #[serde(rename = "Snowboard")]
    Snowboard,
    #[serde(rename = "Snowshoe")]
    Snowshoe,
    #[serde(rename = "Soccer")]
    Soccer,
    #[serde(rename = "Squash")]
    Squash,
    #[serde(rename = "StairStepper")]
    StairStepper,
    #[serde(rename = "StandUpPaddling")]
    StandUpPaddling,
    #[serde(rename = "Surfing")]
    Surfing,
    #[serde(rename = "Swim")]
    Swim,
    #[serde(rename = "TableTennis")]
    TableTennis,
    #[serde(rename = "Tennis")]
    Tennis,
    #[serde(rename = "TrailRun")]
    TrailRun,
    #[serde(rename = "Velomobile")]
    Velomobile,
    #[serde(rename = "VirtualRide")]
    VirtualRide,
    #[serde(rename = "VirtualRow")]
    VirtualRow,
    #[serde(rename = "VirtualRun")]
    VirtualRun,
    #[serde(rename = "Walk")]
    Walk,
    #[serde(rename = "WeightTraining")]
    WeightTraining,
    #[serde(rename = "Wheelchair")]
    Wheelchair,
    #[serde(rename = "Windsurf")]
    Windsurf,
    #[serde(rename = "Workout")]
    Workout,
    #[serde(rename = "Yoga")]
    Yoga,

}

impl std::fmt::Display for SportType {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::AlpineSki => write!(f, "AlpineSki"),
            Self::BackcountrySki => write!(f, "BackcountrySki"),
            Self::Badminton => write!(f, "Badminton"),
            Self::Canoeing => write!(f, "Canoeing"),
            Self::Crossfit => write!(f, "Crossfit"),
            Self::EBikeRide => write!(f, "EBikeRide"),
            Self::Elliptical => write!(f, "Elliptical"),
            Self::EMountainBikeRide => write!(f, "EMountainBikeRide"),
            Self::Golf => write!(f, "Golf"),
            Self::GravelRide => write!(f, "GravelRide"),
            Self::Handcycle => write!(f, "Handcycle"),
            Self::HighIntensityIntervalTraining => write!(f, "HighIntensityIntervalTraining"),
            Self::Hike => write!(f, "Hike"),
            Self::IceSkate => write!(f, "IceSkate"),
            Self::InlineSkate => write!(f, "InlineSkate"),
            Self::Kayaking => write!(f, "Kayaking"),
            Self::Kitesurf => write!(f, "Kitesurf"),
            Self::MountainBikeRide => write!(f, "MountainBikeRide"),
            Self::NordicSki => write!(f, "NordicSki"),
            Self::Pickleball => write!(f, "Pickleball"),
            Self::Pilates => write!(f, "Pilates"),
            Self::Racquetball => write!(f, "Racquetball"),
            Self::Ride => write!(f, "Ride"),
            Self::RockClimbing => write!(f, "RockClimbing"),
            Self::RollerSki => write!(f, "RollerSki"),
            Self::Rowing => write!(f, "Rowing"),
            Self::Run => write!(f, "Run"),
            Self::Sail => write!(f, "Sail"),
            Self::Skateboard => write!(f, "Skateboard"),
            Self::Snowboard => write!(f, "Snowboard"),
            Self::Snowshoe => write!(f, "Snowshoe"),
            Self::Soccer => write!(f, "Soccer"),
            Self::Squash => write!(f, "Squash"),
            Self::StairStepper => write!(f, "StairStepper"),
            Self::StandUpPaddling => write!(f, "StandUpPaddling"),
            Self::Surfing => write!(f, "Surfing"),
            Self::Swim => write!(f, "Swim"),
            Self::TableTennis => write!(f, "TableTennis"),
            Self::Tennis => write!(f, "Tennis"),
            Self::TrailRun => write!(f, "TrailRun"),
            Self::Velomobile => write!(f, "Velomobile"),
            Self::VirtualRide => write!(f, "VirtualRide"),
            Self::VirtualRow => write!(f, "VirtualRow"),
            Self::VirtualRun => write!(f, "VirtualRun"),
            Self::Walk => write!(f, "Walk"),
            Self::WeightTraining => write!(f, "WeightTraining"),
            Self::Wheelchair => write!(f, "Wheelchair"),
            Self::Windsurf => write!(f, "Windsurf"),
            Self::Workout => write!(f, "Workout"),
            Self::Yoga => write!(f, "Yoga"),
        }
    }
}

impl Default for SportType {
    fn default() -> SportType {
        Self::AlpineSki
    }
}

